version: "2"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_DATABASE: drinks
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: marty
      MYSQL_PASSWORD: h&PT93QX6SibJf#
    volumes:
      - my-datavolume:/var/www/mysql
  app:
    restart: always
    build: ./
    links:
      - db
    ports:
      - "5000:5000"
    environment:
      - VIRTUAL_HOST=api.atmarty.com
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
volumes:
  my-datavolume: